baseURL = "https://example.com/"
locale = "ro"
title = "CORA"
defaultContentLanguage = "ro"
defaultContentLanguageInSubdir = false

[params]
  city = "Chișinău"
  product = "CORA"
  tagline = "CORA — financial freedom without borders"
  googleFormsEndpoint = "https://script.google.com/macros/s/AKfycbwb3C-8-bIIivV0Q0e7ih15LKuagj2zkJPZKstjyRE46Ev20pFvM3_mMvNNm30jwaUVmQ/exec"

[languages]

  [languages.ro]
    locale = "ro"
    label = "Română"
    weight = 1
    contentDir = "content/ro"

  [languages.en]
    locale = "en"
    label = "English"
    weight = 2
    contentDir = "content/en"

  [languages.ru]
    locale = "ru"
    label = "Русский"
    weight = 3
    contentDir = "content/ru"
